---
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: main

requires:
  - configs: [ ]
    path: k8s/skaffold.yaml

  - configs: [ ]
    path: service0/skaffold.yaml

  - configs: [ ]
    path: service1/skaffold.yaml