---
apiVersion: skaffold/v2beta28
kind: Config
profiles:
  - name: local
    activation:
      - kubeContext: minikube
    deploy:
      # statusCheck: false
      kubeContext: minikube
      kubectl:
        defaultNamespace: gosample-local
        manifests:
          - k8s/local/*.yaml
    build:
      artifacts:
      - image: dragonqos/service0
        context: ./